spring:
  application:
    name: travel-gateway

  # TODO Configure token forwarding
  cloud:
    gateway:
      routes:
        # this route can be used to see how/if the token is send to the backend
        # i.e. using curl -H "Cookie: <your_cookie>" http://localhost:8080/httpbin/test
        - id: httpbin
          uri: https://httpbin.org
          predicates:
          - Path=/httpbin/**
          filters:
          - StripPrefix=1

        - id: flights-service
          uri: http://127.0.0.1:8081/flights
          predicates:
          - Path=/flights/**

        - id: hotels-service
          uri: http://127.0.0.1:8082/hotels
          predicates:
          - Path=/hotels/**


# TODO Configure authentication through Keycloak
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/auth/realms/spring-cloud-gateway-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring-cloud-gateway-client
            client-secret: <your_secret>